apiVersion: v1
kind: Service
metadata:
  name: tubes-devops-service
  namespace: tubes-devops
  labels:
    app: tubes-devops
spec:
  type: ClusterIP
  selector:
    app: tubes-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  sessionAffinity: ClientIP
